time_zone: "Hanoi"
email:
  time_expired: 2
role:
  admin: "admin"
  trainee: "trainee"
avatar:
  size: 50
  size_in_show: 150
course_form:
  description:
    rows: 3
course:
  number_of_description: 200
  status_start: 1
  status_finish: 2
subject_course:
  status_start: 1
  status_finish: 2
user_subject:
  status:
    default_status: 0
    status_start: 1
    finish_status: 2
target_type:
  task: 1
  update_course: 1
tasks:
  complete: 100
  start: 0
